2020-04-16 19:49:11.2656 ERROR Something went wrong inside GetAllOwners action : An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
2020-04-16 19:49:56.8952 INFO Returned all (System.Collections.Generic.List`1[Entities.Models.Owner]) owners from database
2020-04-16 19:53:56.2509 INFO Returned all (System.Collections.Generic.List`1[Entities.Models.Owner]) owners from database
2020-04-16 19:59:52.4772 INFO Returned all (System.Collections.Generic.List`1[Entities.Models.Owner]) owners from database
2020-04-16 20:02:03.2607 INFO Returned all (System.Collections.Generic.List`1[Entities.Models.Owner]) owners from database
2020-04-16 21:27:33.6182 INFO Returned all (System.Collections.Generic.List`1[Entities.Models.Owner]) owners from database
2020-04-16 21:27:37.2444 INFO Returned all (System.Collections.Generic.List`1[Entities.Models.Owner]) owners from database
2020-04-16 21:27:56.6535 INFO Returned all (System.Collections.Generic.List`1[Entities.Models.Owner]) owners from database
2020-04-16 21:28:26.3392 INFO Returned all (System.Collections.Generic.List`1[Entities.Models.Owner]) owners from database
